### ISSUE TITLE
Write tests for all functions and renderings

### ISSUE THREAD

**Issue by hagenbrandt** [hagenbrandt/the-dive-book#44]
# Value statement
# Description

- Write tests for all functions and renderings. Use the react-testing-library for it, if necessary use jest also.

# Tasks

- [ ] Install react testing library

- [ ] Write tests for all functions

- [ ] Write render tests for all components

# Size
Large
