### ISSUE TITLE
Make edit on logs work

### ISSUE THREAD

**Issue by hagenbrandt** [hagenbrandt/the-dive-book#48]
# Value statement
# Description

- It should be possible to edit own logs.

# Tasks

- [ ] Add icon to nav bar

- [ ] Create a new route

- [ ] Create new design for edit page

- [ ] Create new site with logs.

- [ ] Write logic to edit logs.

- [ ] Write tests

# Size
Large
